Repository UHH2/UHH2, pull requests merged in 2018-11, with the labels that each got.

#1042 fixes for Modified MET
  common/include/JetCorrections.h
  common/include/PrintingModules.h
  common/src/JetCorrections.cxx
  common/src/PrintingModules.cxx
  core/python/ntuplewriter.py
  core/python/ntuplewriter_addL1seed.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_MC.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_wGenParticles_MC.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_wGenParticles_wModifiedMET_DATA.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_wGenParticles_wModifiedMET_MC.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_woTriggerObjects_wLowPtjets_wXCONE.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woXCONE_woTopJets.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woXCONE_woTopJets_lowPtjets.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woXCONE_woTopJets_woTriggerObjects_wLowPtjets.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woXCONE_woTopJets_woTriggerObjects_wLowPtjets_MC.py
  core/python/ntuplewriter_uprefirableFilter.py
  core/python/ntuplewriter_woHOTVR_woXCONE.py
  core/python/ntuplewriter_woHOTVR_woXCONE_MC.py
Labels: Passed

#1043 [94X_v3] Update to electron V2 cut & MVA IDs from V1
  core/include/Electron.h
  core/python/ntuplewriter.py
Labels: Passed

#1044 [94X_v3] Add example electron ID module, update electron eff area file
  core/python/ntuplewriter.py
  examples/config/ExampleElectronID.xml
  examples/src/ExampleModuleElectronID.cxx
Labels: Passed

#1045 [102X] Setup install script, fixes for C++17
  Makefile.common
  core/include/AnalysisModuleRunner.h
  core/include/obj.h
  core/include/registry.h
  core/src/AnalysisModuleRunner.cxx
  scripts/install.sh
Labels: Passed

#1048 [102X] Remove unnecessary cms-addpkg
  scripts/install.sh
Labels: Passed

#1050 [102X] Add CMSSW flags to fastjet(-contrib) compilation, including optimisation & more error checking
  scripts/install.sh
Labels: Passed

#1051 [102X] Remove HOTVR jets with CHS input
  core/python/ntuple_generator.py
Labels: Passed

#1053 [102X] Downgrade GenXCone lepton warnings
  core/plugins/GenXConeProducer.cc
Labels: Passed

#1058 JER SF V3 derived from Pythia and Madgraph samples
  common/include/JetCorrections.h
  common/src/JetCorrections.cxx
Labels: Failed

#1054 [102X] Make ntuples handle different years; add in example CMSSW configs for each, & now handles command line args
  .gitignore
  core/python/copyMiniAODInputs.py
  core/python/ntuple_generator.py
  core/python/ntuplewriter_data.py
  core/python/ntuplewriter_data_2016v2.py
  core/python/ntuplewriter_data_2016v3.py
  core/python/ntuplewriter_data_2017.py
  core/python/ntuplewriter_data_2018.py
  core/python/ntuplewriter_mc.py
  core/python/ntuplewriter_mc_2016v2.py
  core/python/ntuplewriter_mc_2016v3.py
  core/python/ntuplewriter_mc_2017.py
  core/python/ntuplewriter_mc_2018.py
  core/python/optionsParse.py
Labels: Passed

#1060 [102X] Fix trigger prescale access; trigger collection for 2016v2; trigger example
  core/include/Event.h
  core/python/ntuple_generator.py
  core/src/Event.cxx
  examples/config/ExampleTrigger.xml
  examples/src/ExampleModuleTrigger.cxx
Labels: Passed :smile:
