Repository UHH2/UHH2, pull requests merged in 2018-12, with the labels that each got.

#1061 [102X] Add L1 prefire weights
  core/include/Event.h
  core/include/EventHelper.h
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/python/ntuple_generator.py
  core/src/Event.cxx
  core/src/EventHelper.cxx
  examples/src/ExampleModuleTrigger.cxx
  scripts/install.sh
Labels: Passed

#1062 [102X] Add note to setup L1 prefiring for CRAB jobs, update crab_template as well
  core/python/ntuple_generator.py
  scripts/crab/crab_template.py
Labels: Passed

#1059 Fixed bug in type-1 correction of PuppiMET
  common/src/JetCorrections.cxx
Labels: Passed

#1064 [94Xv2] Remove configs with modifiedMet
  core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_wGenParticles_wModifiedMET_DATA.py
  core/python/ntuplewriter_addL1seed_woHOTVR_woTopJets_wTriggerObjects_wLowPtjets_wXCONE_wGenParticles_wModifiedMET_MC.py
Labels: TestsRunning

#1063 [102X] Port: Fixed critical bug in type-1 correction of Puppi-MET
  common/src/JetCorrections.cxx
Labels: Passed

#1065 [94Xv2] Port: Fixed critical bug in type-1 correction of Puppi-MET
  common/src/JetCorrections.cxx
Labels: Passed

#1066 [94Xv3] Port: Fixed critical bug in type-1 correction of Puppi-MET
  common/src/JetCorrections.cxx
Labels: Passed

#1069 Implemented (working) JEC/JER V32
  common/data/Fall17_V3_MC_PtResolution_AK4PFPuppi.txt
  common/data/Fall17_V3_MC_PtResolution_AK4PFchs.txt
  common/data/Fall17_V3_MC_PtResolution_AK8PFPuppi.txt
  common/data/Fall17_V3_MC_PtResolution_AK8PFchs.txt
  common/include/CommonModules.h
  common/include/JetCorrectionSets.h
  common/include/JetCorrections.h
  common/src/CommonModules.cxx
  common/src/JetCorrectionSets.cxx
  common/src/JetCorrections.cxx
Labels: Passed

#1070 [102X] CRAB tarball creator & checker, updates to DasQuery
  scripts/crab/DasQuery.py
  scripts/crab/crab_template.py
  scripts/crab/makeCheckCrabTarball.py
Labels: Passed

#1072 [102X] Comment out wrong L1 prefire file location
  core/python/ntuple_generator.py
Labels: Failed

#1074 merge of JEC and JER between branch 94X_v2 and 94X_v3
  common/include/JetCorrections.h
  common/src/JetCorrections.cxx
Labels: Failed

#1081 [94Xv1] Remove .git from EGamma external files as inflates CRAB tarball
  scripts/install.sh
Labels: Passed, RunII_94X_v1

#1080 [94Xv2] Remove .git from EGamma external files as inflates CRAB tarball
  scripts/install.sh
Labels: Passed, RunII_94X_v2

#1082 [94Xv3] Remove old EGamma ID files during installation to slim CRAB tarball
  scripts/install.sh
Labels: Passed, RunII_94X_v3
