Repository UHH2/UHH2, pull requests merged in 2019-02, with the labels that each got.

#1112 [102_X] Proper pat jets for RECO xcone and hotvr
  core/plugins/GenHOTVRProducer.cc
  core/plugins/GenXConeProducer.cc
  core/plugins/HOTVRProducer.cc
  core/plugins/NtupleWriter.cc
  core/plugins/XConeProducer.cc
Labels: Passed, RunII_102X_v1

#1114 [102X] Add ECAL bad crystal filter bool
  core/include/Event.h
  core/include/EventHelper.h
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/python/ntuple_generator.py
  core/src/Event.cxx
  core/src/EventHelper.cxx
Labels: Passed, RunII_102X_v1

#1115 [102X] Bad muon & bad charged filters for 2016v2
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1116 [102X] Store pileup working points
  core/include/Jet.h
  core/plugins/NtupleWriterJets.cxx
  examples/config/ExampleJetTags.xml
  examples/src/ExampleModuleJetTags.cxx
Labels: Passed, RunII_102X_v1

#1117 [102X] Recluster AK8PUPPI for TopJets ourselves
  core/plugins/NtupleWriterJets.cxx
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1119 [102X] Set btag discriminant defaults to impossible value
  core/include/Jet.h
Labels: Passed, RunII_102X_v1

#1118 [102X] add storage of PF candidates for selected number of reconstructed jets
  core/include/EventHelper.h
  core/include/Jet.h
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/plugins/NtupleWriterJets.cxx
  core/plugins/NtupleWriterJets.h
  core/plugins/XConeProducer.cc
  core/python/ntuple_generator.py
  core/src/EventHelper.cxx
Labels: Passed, RunII_102X_v1

#1120 [102X] Better Jet/TopJet collection names
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1121 [102X] add CHS MET for 2016 data
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1122 [102X] Add in extra slimmed METs specific for 03Feb2017 data
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1123 [102X] Add b-tagging shape systematic for CSV
  README.md
  common/include/BTagCalibrationStandalone.h
  common/include/MCWeight.h
  common/src/BTagCalibrationStandalone.cc
  common/src/MCWeight.cxx
Labels: Passed, RunII_102X_v1

#1125 [102X] Rename `slimmedJets` -> `jetsAk4CHS` using dummy selector
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1124 [102X] Add missing variables for b-tagging
  core/include/Jet.h
  core/plugins/NtupleWriterJets.cxx
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1126 [102X] add Photons
  core/include/Photon.h
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriterLeptons.cxx
  core/plugins/NtupleWriterLeptons.h
  core/plugins/PATPhotonUserData.cc
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1127 [102X] add DeepBoosted info to AK8CHS jets
  core/include/Jet.h
  core/include/TopJet.h
  core/plugins/NtupleWriterJets.cxx
  core/plugins/NtupleWriterJets.h
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1128 [102X] Update Electron ID module to do electrons + photons, rename it
  examples/config/ExampleEGammaID.xml
  examples/src/ExampleModuleEGammaID.cxx
Labels: Passed, RunII_102X_v1

#1131 [102X] Lower fatjet_ptmin to account for JECs
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1129 [102X] GenTopJet substructure vars
  core/include/GenTopJet.h
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1132 [102X] calculate and store PUPPI multiplicities only for PUPPI jets
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1134 [102X] add more flags for PF/GEN constituents storing
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/plugins/NtupleWriterJets.cxx
  core/plugins/NtupleWriterJets.h
  core/python/ntuple_generator.py
Labels: Failed, RunII_102X_v1

#1133 [102X] Drop taus from NTuples
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1137 [102X] GenJet multiplicities
  core/include/GenJet.h
  core/plugins/NtupleWriter.cc
Labels: Passed, RunII_102X_v1

#1136 [102X] add more flags for PF/GEN constituents storing
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/plugins/NtupleWriterJets.cxx
  core/plugins/NtupleWriterJets.h
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1138 [102X] switch off collection/storage not needed by defualt
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1141 [102X] remove duplication from b-tagging list
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1142 [102X] Update trigger example with hist
  examples/config/ExampleTrigger.xml
  examples/src/ExampleModuleTrigger.cxx
Labels: Passed, RunII_102X_v1

#1140 [102X] disable warnings from patJetUpdater and (Gen)XconeProducer
  core/plugins/GenXConeProducer.cc
  core/plugins/XConeProducer.cc
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1139 added Muon and Electron GenJets
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1143 [102X] Turn off photon puppi isolation for 2016v2
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriterLeptons.cxx
  core/plugins/NtupleWriterLeptons.h
Labels: Passed, RunII_102X_v1

#1144 [102X] Disable lepton genjets by default
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1145 [102X] update JECs
  common/datasets/RunII_102X_v1/2016v2/MC_RSGluonToTT_M-4000_2016v2.xml
  common/datasets/RunII_102X_v1/2017/MC_RSGluonToTT_M-4000_2017.xml
  common/datasets/RunII_102X_v1/2018/MC_ZprimeToTT_M1500_W450_2018.xml
  common/include/CommonModules.h
  common/include/JetCorrectionSets.h
  common/include/JetCorrections.h
  common/src/CommonModules.cxx
  common/src/JetCorrectionSets.cxx
  common/src/JetCorrections.cxx
  common/test/TestJetCorrections.cpp
  common/test/test_JER.cpp
  common/test/test_JLCkey.cpp
Labels: Passed, RunII_102X_v1

#1146 [102X] Replace auto_ptr with make_shared
  common/src/BTagCalibrationStandalone.cc
Labels: Passed, RunII_102X_v1

#1147 test signal samples for Z' analysis
  common/datasets/RunII_102X_v1/2016v2/MC_ZprimeToTT_M4000_W400_2016v2TEST.xml
  common/datasets/RunII_102X_v1/2017/MC_ZprimeToTT_M4000_W400_2017TEST.xml
  common/datasets/RunII_102X_v1/2018/MC_ZprimeToTT_M4000_W400_2018TEST.xml
Labels: Passed, RunII_102X_v1

#1148 [102X] update JetID cuts
  common/include/JetIds.h
  common/src/CommonModules.cxx
  common/src/JetIds.cxx
  common/test/test_JER.cpp
  common/test/test_JLCkey.cpp
Labels: Passed, RunII_102X_v1

#1153 [102X] fix silly mistake in 2018 JetID
  common/src/JetIds.cxx
Labels: Passed, RunII_102X_v1

#1149 [102X] Fix higgs tagging variables for AK8 Puppi TopJets
  core/include/TopJet.h
  core/python/ntuple_generator.py
  examples/config/ExampleJetTags.xml
  examples/src/ExampleModuleJetTags.cxx
Labels: Passed, RunII_102X_v1

#1150 [102X] Tidy up extra genparticle storage options
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1154 [102X] electronID fixes
  common/include/ElectronIds.h
  common/src/ElectronIds.cxx
  common/src/JetIds.cxx
  common/test/test_JLCkey.cpp
  core/include/Electron.h
  core/python/ntuple_generator.py
  examples/src/ExampleModule2.cxx
  examples/src/ExampleModuleEGammaID.cxx
Labels: Passed, RunII_102X_v1

#1151 [102X] fill GenTopJet genparticles, add jet constituent example
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/src/AnalysisModuleRunner.cxx
  examples/config/Example.xml
  examples/config/ExampleJetConstituents.xml
  examples/src/ExampleModuleJetConstituents.cxx
Labels: Passed, RunII_102X_v1

#1152 [102X] Fix jet L1 correction factor stored in ntuplewriter
  core/include/Jet.h
  core/plugins/NtupleWriterJets.cxx
Labels: Passed, RunII_102X_v1

#1156 [102X] Cleaning in common/data directory
  common/data/2016/CSVv2_Moriond17_B_H.csv
  common/data/2016/Spring16_25nsV10_MC_PtResolution_AK4PFchs.txt
  common/data/2016/Spring16_25nsV10_MC_PtResolution_AK8PFchs.txt
  common/data/2016/general_eff_aeta_dr030e030_corr_ratio.txt
  common/data/2016/subjet_CSVv2_Moriond17_B_H.csv
  common/data/2017/Fall17_V3_MC_PtResolution_AK4PFPuppi.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK4PFchs.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK8PFPuppi.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK8PFchs.txt
  common/data/CSVv2_ichep.csv
  common/data/Cert_271036-273450_13TeV_PromptReco_Collisions16_JSON_NoL1T.root
  common/data/Cert_271036-273730_13TeV_PromptReco_Collisions16_JSON.root
  common/data/Cert_271036-284044_13TeV_23Sep2016ReReco_Collisions16_JSON.root
  common/data/HLT_Mu45_eta2p1_TriggEff_DATA_4fb.root
  common/data/MuonID_EfficienciesAndSF_BCDEF.root
  common/data/MuonID_EfficienciesAndSF_GH.root
  common/data/MuonID_EfficienciesAndSF_average_RunBtoH.root
  common/data/MuonID_Z_2016runB_2p6fb.root
  common/data/MuonIso_EfficienciesAndSF_BCDEF.root
  common/data/MuonIso_EfficienciesAndSF_GH.root
  common/data/MuonIso_EfficienciesAndSF_average_RunBtoH.root
  common/data/MuonTrigger_EfficienciesAndSF_RunBtoF.root
  common/data/MuonTrigger_EfficienciesAndSF_RunGtoH.root
  common/data/MuonTrigger_EfficienciesAndSF_average_RunBtoH.root
  common/data/MyDataPileupHistogram.root
  common/data/MyDataPileupHistogram_66017.root
  common/data/MyDataPileupHistogram_72383.root
  common/data/MyDataPileupHistogram_80000.root
  common/data/MyMCPileupHistogram.root
  common/data/Pt_vs_Eta__HLT_Mu45_eta2p1__SF.root
  common/data/egammaEffi.txt_EGM2D_CutBased_Loose_ID.root
  common/data/egammaEffi.txt_EGM2D_CutBased_Medium_ID.root
  common/data/egammaEffi.txt_EGM2D_CutBased_Tight_ID.root
  common/data/egammaEffi.txt_EGM2D_MVA80_ID.root
  common/data/egammaEffi.txt_EGM2D_MVA90_ID.root
  common/data/egammaEffi.txt_EGM2D_RecEff_Moriond17.root
  common/data/egammaEffi.txt_SF2D_TightCutBased_0_5fb.root
  common/data/egammaEffi.txt_SF2D_TightCutBased_5fb.root
  common/data/lumiAnomalies_2016_170301_JSON.root
  common/datasets/RunII_102X_v1/2018/MC_QCD_Flat2018_TMP.xml
Labels: RunII_102X_v1, TestsRunning

#1157 [102X] Remove/void unused vars in methods
  examples/src/ExampleModuleJetConstituents.cxx
Labels: Passed, RunII_102X_v1

#1158 [102X] Fix bug when deciding to store jet PFcands; add test plots
  core/plugins/NtupleWriterJets.cxx
  core/python/ntuple_generator.py
  examples/src/ExampleModuleJetConstituents.cxx
Labels: Passed, RunII_102X_v1

#1160 [102X] add stuff for advanced trigger studies
  core/include/Event.h
  core/include/EventHelper.h
  core/include/L1EGamma.h
  core/include/L1Jet.h
  core/include/NtupleObjects.h
  core/include/SUHH2core_LinkDef.h
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/python/ntuple_generator.py
  core/src/AnalysisModuleRunner.cxx
  core/src/EventHelper.cxx
  core/src/classes.h
  core/src/classes_def.xml
Labels: Passed, RunII_102X_v1

#1161 [102X] add missing data files
  common/data/2016/Cert_271036-284044_13TeV_23Sep2016ReReco_Collisions16_JSON.root
  common/data/2016/MuonID_EfficienciesAndSF_BCDEF.root
  common/data/2016/MuonID_EfficienciesAndSF_GH.root
  common/data/2016/MuonID_EfficienciesAndSF_average_RunBtoH.root
  common/data/2016/MuonID_Z_2016runB_2p6fb.root
  common/data/2016/MuonIso_EfficienciesAndSF_BCDEF.root
  common/data/2016/MuonIso_EfficienciesAndSF_GH.root
  common/data/2016/MuonIso_EfficienciesAndSF_average_RunBtoH.root
  common/data/2016/MuonTrigger_EfficienciesAndSF_RunBtoF.root
  common/data/2016/MuonTrigger_EfficienciesAndSF_RunGtoH.root
  common/data/2016/MuonTrigger_EfficienciesAndSF_average_RunBtoH.root
  common/data/2016/MyDataPileupHistogram.root
  common/data/2016/MyDataPileupHistogram_66017.root
  common/data/2016/MyDataPileupHistogram_72383.root
  common/data/2016/MyDataPileupHistogram_80000.root
  common/data/2016/MyMCPileupHistogram.root
  common/data/2016/Pt_vs_Eta__HLT_Mu45_eta2p1__SF.root
  common/data/2016/egammaEffi.txt_EGM2D_CutBased_Loose_ID.root
  common/data/2016/egammaEffi.txt_EGM2D_CutBased_Medium_ID.root
  common/data/2016/egammaEffi.txt_EGM2D_CutBased_Tight_ID.root
  common/data/2016/egammaEffi.txt_EGM2D_MVA80_ID.root
  common/data/2016/egammaEffi.txt_EGM2D_MVA90_ID.root
  common/data/2016/egammaEffi.txt_EGM2D_RecEff_Moriond17.root
  common/data/2016/egammaEffi.txt_SF2D_TightCutBased_0_5fb.root
  common/data/2016/egammaEffi.txt_SF2D_TightCutBased_5fb.root
  common/data/2016/lumiAnomalies_2016_170301_JSON.root
  common/data/2017/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.root
  common/data/2017/MuonID_94X_RunBCDEF_SF_ID.root
  common/data/2017/MuonTrigger_EfficienciesAndSF_RunBtoF_Nov17Nov2017.root
  common/data/2017/MyDataPileupHistogram.root
  common/data/2017/MyDataPileupHistogram_66017.root
  common/data/2017/MyDataPileupHistogram_72383.root
  common/data/2017/MyMCPileupHistogram.root
  common/data/2018/tmp.txt
  common/datasets/RunII_102X_v1/DATA_Run2018D_JetHT_TEST.xml
Labels: RunII_102X_v1, TestsRunning

#1162 [102X] Use NtupleWriter class for GenTopJets, do substructure+grooming properly
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/plugins/NtupleWriterJets.cxx
  core/plugins/NtupleWriterJets.h
  core/python/ntuple_generator.py
  examples/config/ExampleJetConstituents.xml
  examples/src/ExampleModuleJetConstituents.cxx
Labels: Passed, RunII_102X_v1

#1164 [102X] generic callable electron IDs
  common/include/ElectronIds.h
  examples/src/ExampleModuleEGammaID.cxx
Labels: Passed, RunII_102X_v1

#1165 [102X] rename gen top jet collections
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1166 [102X] tmp of examples for jet composition checks
  examples/config/ExampleJetComposition.xml
  examples/config/ExampleJetConstituents.xml
  examples/src/ExampleHists.cxx
  examples/src/ExampleJetComposition.cxx
Labels: Passed, RunII_102X_v1

#1163 [102X] add b-taggers WPs for AK4 jets, rename Jet::btag_DeepFlavour() to Jet::btag_DeepJet(), specify era of process
  common/include/JetHists.h
  common/include/JetIds.h
  common/include/MCWeight.h
  common/src/JetIds.cxx
  core/include/AnalysisModule.h
  core/include/Jet.h
  core/python/ntuple_generator.py
  scripts/compare_hists.C
Labels: Passed, RunII_102X_v1

#1168 temporary files for JER testing
  common/datasets/RunII_102X_v1/2018/DATA_JetHT2018A_TMP.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Flat2018_TMP.xml
  examples/config/ExampleJetComposition.xml
  examples/config/ExampleJetConstituents.xml
  examples/src/ExampleModuleJetComposition.cxx
  examples/src/ExampleModuleJetConstituents.cxx
Labels: RunII_102X_v1, TestsRunning

#1169 [102X] add GenJet cleaning and printing as in 94X_v3
  common/include/CleaningModules.h
  common/include/JetCorrections.h
  common/include/ObjectIdUtils.h
  common/include/PrintingModules.h
  common/src/CleaningModules.cxx
  common/src/JetCorrections.cxx
  common/src/PrintingModules.cxx
Labels: Passed, RunII_102X_v1

#1167 [102X] Split 2017 config settings into 2017v1 & 2017v2
  core/python/ntuple_generator.py
  core/python/ntuplewriter_data_2017v2.py
  core/python/ntuplewriter_mc_2017v1.py
  core/python/ntuplewriter_mc_2017v2.py
Labels: Passed, RunII_102X_v1

#1174 [102X] 97% of Flat18 QCD, 70% of RunA data, fix bug for L1RC of 2018 JECs
  common/datasets/RunII_102X_v1/2018/DATA_JetHT2018A_TMP.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Flat2018_TMP.xml
  common/src/JetCorrectionSets.cxx
  examples/config/ExampleJetConstituents.xml
Labels: Passed, RunII_102X_v1

#1173 Lumi & PU files
  common/data/2017/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1.root
  common/data/2017/Cert_294927-306462_13TeV_EOY2017ReReco_Collisions17_JSON_v1_wonormTag.root
  common/data/2017/MyDataPileupHistogram2017.root
  common/data/2017/MyDataPileupHistogram2017_66017.root
  common/data/2017/MyDataPileupHistogram2017_72383.root
  common/data/2018/Cert_314472-325175_13TeV_PromptReco_Collisions18_JSON.root
  common/data/2018/Cert_314472-325175_13TeV_PromptReco_Collisions18_JSON_wonormTag.root
  common/data/2018/MyDataPileupHistogram2018.root
  common/data/2018/MyDataPileupHistogram2018_66017.root
  common/data/2018/MyDataPileupHistogram2018_72383.root
  common/data/2018/tmp.txt
  common/src/JetCorrectionSets.cxx
Labels: Passed, RunII_102X_v1

#1172 [102X] Handle extra 2017 year for JetIDs
  common/src/JetIds.cxx
Labels: Passed, RunII_102X_v1

#1175 [102X] Add script to iterate over XMLs and find ntuples
  scripts/findAllNtupleDirs.py
Labels: RunII_102X_v1
