Repository UHH2/UHH2, pull requests merged in 2019-04, with the labels that each got.

#1214 Added at csh version of the script
  scripts/install.csh
Labels: RunII_102X_v1

#1218 [102X] Add Year enum; update MET filters in CommonModules; fixes for JetResolutionSmearer
  common/include/CommonModules.h
  common/include/Utils.h
  common/src/CommonModules.cxx
  common/src/JetCorrections.cxx
  common/src/Utils.cxx
Labels: Passed, RunII_102X_v1

#1221 [102X] Improve JetResolutionSmearer
  common/include/JetCorrections.h
  common/src/JetCorrections.cxx
  core/include/Utils.h
  core/src/Utils.cxx
Labels: Passed, RunII_102X_v1

#1223 [102X] increase default pt for jet constituence storage
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriterJets.cxx
Labels: Passed, RunII_102X_v1

#1233 Processed DiBoson Samples
  common/datasets/RunII_102X_v1/2018/MC_WW_TuneCP5_13TeV-pythia8.xml
  common/datasets/RunII_102X_v1/2018/MC_WZ_TuneCP5_13TeV-pythia8.xml
  common/datasets/RunII_102X_v1/2018/MC_ZZ_TuneCP5_13TeV-pythia8.xml
Labels: RunII_102X_v1

#1234 [102X] copy of TTbarGen fix from 80X_v3
  common/src/TTbarGen.cxx
Labels: Passed, RunII_102X_v1

#1236 Inclusive Single Top Sample
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_antitop_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.xml
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_top_5f_inclusiveDecays_TuneCP5_13TeV-powheg-pythia8.xml
Labels: RunII_102X_v1

#1237 [102X] Update locate_file(), use in various modules
  common/include/Utils.h
  common/src/LumiSelection.cxx
  common/src/LuminosityHists.cxx
  common/src/MCWeight.cxx
  common/src/Utils.cxx
Labels: Passed, RunII_102X_v1

#1238 [102X] Add printout of CommonModules setup after init
  common/include/CommonModules.h
  common/src/CommonModules.cxx
Labels: Passed, RunII_102X_v1

#1241 Run ii 102 x v1
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_antitop_5f_NoFullyHadronicDecays.xml
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_antitop_5f_NoFullyHadronicDecays_ext1-v2.xml
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_antitop_5f_NoFullyHadronicDecays_ext1-v3.xml
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_antitop_5f_inclusiveDecays.xml
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_top_5f_NoFullyHadronicDecays.xml
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_top_5f_NoFullyHadronicDecays_ext1-v2.xml
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_top_5f_NoFullyHadronicDecays_ext1-v3.xml
  common/datasets/RunII_102X_v1/2018/MC_ST_tW_top_5f_inclusiveDecays.xml
Labels: RunII_102X_v1

#1240 [102X] More MET filter updates
  common/src/CommonModules.cxx
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1242 [102X] Update example configs
  examples/config/Example.xml
  examples/config/Example2.xml
  examples/config/ExampleComposing.xml
  examples/config/ExampleEGammaID.xml
  examples/config/ExampleEventInput.xml
  examples/config/ExampleEventInput2.xml
  examples/config/ExampleEventOutput.xml
  examples/config/ExampleJetComposition.xml
  examples/config/ExampleJetConstituents.xml
  examples/config/ExampleJetTags.xml
  examples/config/ExampleMuonID.xml
  examples/config/ExampleTTbarGen.xml
  examples/config/ExampleTTbarRec.xml
  examples/config/ExampleTrigger.xml
  examples/config/GenParticlesPrinter.xml
  examples/config/MakePileupHistMC.xml
Labels: RunII_102X_v1

#1243 [102X] New definition of BTagEffiHists class with templates
  common/include/JetHists.h
  common/src/JetHists.cxx
Labels: Passed, RunII_102X_v1

#1244 Run ii 102 x v1
  common/include/JetCorrections.h
  common/src/JetCorrections.cxx
  core/include/GenTopJet.h
Labels: Passed, RunII_102X_v1

#1246 [102X] Add ability to store extra trigger bits; use for BadPFMuonFilter instead of in veto mode
  common/src/CommonModules.cxx
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1249 [102X_v1] ttbar 2016v3 samples
  common/datasets/RunII_102X_v1/2016v3/MC_TT_Mtt-1000toInf.xml
  common/datasets/RunII_102X_v1/2016v3/MC_TT_Mtt-700to1000.xml
  common/datasets/RunII_102X_v1/2016v3/MC_TT_TuneCUETP8M2T4.xml
Labels: RunII_102X_v1, TestsRunning

#1250 Enriched 2018 QCD MC XML [skip ci]
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-1000toInf_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-120to170_EMEnriched.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-120to170_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-120to170_MuEnrichedPt5_ext1-v2.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-15to20_EMEnriched_ext1-v2.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-15to20_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-170to300_EMEnriched.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-170to300_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-20to30_EMEnriched.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-20to30_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-300to470_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-300to470_MuEnrichedPt5_ext3-v1.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-300toInf_EMEnriched.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-30to50_EMEnriched_ext1-v2.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-30to50_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-470to600_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-470to600_MuEnrichedPt5_ext1-v2.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-50to80_EMEnriched.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-50to80_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-600to800_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-800to1000_MuEnrichedPt5_ext3-v2.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-80to120_EMEnriched.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-80to120_MuEnrichedPt5.xml
  common/datasets/RunII_102X_v1/2018/MC_QCD_Pt-80to120_MuEnrichedPt5_ext1-v2.xml
Labels: RunII_102X_v1, TestsRunning

#1251 [skip ci]
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-100to200.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-200to400.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-2500toInf.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-400to600.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-400to600_v2.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-400to600_v3.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-400to600_v4.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-400to600_v7.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-600to800.xml
  common/datasets/RunII_102X_v1/2018/MC_DYJetsToLL_M-50_HT-800to1200.xml
  common/datasets/RunII_102X_v1/2018/MC_TTTo2L2Nu.xml
  common/datasets/RunII_102X_v1/2018/MC_TTToSemiLeptonic_mtop166p5.xml
  common/datasets/RunII_102X_v1/2018/MC_TTToSemiLeptonic_mtop178p5.xml
  common/datasets/RunII_102X_v1/2018/MC_ZprimeToTT_M1000_W10.xml
  common/datasets/RunII_102X_v1/2018/MC_ZprimeToTT_M1500_W15.xml
  common/datasets/RunII_102X_v1/2018/MC_ZprimeToTT_M2500_W25.xml
  common/datasets/RunII_102X_v1/2018/MC_ZprimeToTT_M3000_W30.xml
  common/datasets/RunII_102X_v1/2018/MC_ZprimeToTT_M500_W5.xml
  common/datasets/RunII_102X_v1/2018/MC_ZprimeToTT_M750_W7p5.xml
Labels: RunII_102X_v1, TestsRunning

#1253 [ci skip] add SingleMuon2018_RunC
  common/datasets/RunII_102X_v1/2018/DATA_SingleMuon2018_RunC.xml
Labels: RunII_102X_v1

#1254 Add Github PR template
  pull_request_template.md
Labels: master
