Repository UHH2/UHH2, pull requests merged in 2019-03, with the labels that each got.

#1181 [102X] Fix JEC preprocessor macros to avoid memory hog, slowdown
  common/src/JetCorrectionSets.cxx
Labels: Passed, RunII_102X_v1

#1180 [102X] Add JEC V7 for JERC studies with 2018 data
  common/datasets/RunII_102X_v1/2018/MC_QCD_Flat2018_TMP.xml
  common/include/JetCorrectionSets.h
  common/src/JetCorrectionSets.cxx
Labels: Passed, RunII_102X_v1

#1183 [102X] 2018 JEC for Moriond19
  common/datasets/RunII_102X_v1/2018/DATA_JetHT2018C.xml
  common/datasets/RunII_102X_v1/RelVals_105rel2/MC_QCD_Flat_105X_realistic_v2_Hcal_Ref.xml
  common/datasets/RunII_102X_v1/RelVals_105rel2/MC_QCD_Flat_105X_upgrade2018_realistic_v2_oldTrk.xml
  common/include/JetCorrectionSets.h
  common/src/JetCorrectionSets.cxx
Labels: Passed, RunII_102X_v1

#1185 [102X] copy most of slimmed b-taggers from miniAOD
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1186 [102X] Remove unused or nonexistent trigger objects
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1192 [102X] Add cmssw config to run with all jet constituents stored
  core/python/ntuplewriter_mc_2018_allConstits.py
Labels: Passed, RunII_102X_v1

#1193 [102X] Puppi weights + tidying for jet constituents
  core/include/Utils.h
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriterJets.cxx
  core/plugins/NtupleWriterJets.h
  core/src/Utils.cxx
Labels: Passed, RunII_102X_v1

#1195 [102X] Get PUPPI userFloats by matching strings to ignore producer's name
  core/plugins/NtupleWriterJets.cxx
  core/plugins/NtupleWriterJets.h
Labels: Passed, RunII_102X_v1

#1196 [102X] cleanup HOTVR headers from XCone producers
  core/plugins/GenHOTVRProducer.cc
  core/plugins/GenXConeProducer.cc
  core/plugins/HOTVRProducer.cc
  core/plugins/XConeProducer.cc
Labels: Failed, RunII_102X_v1

#1197 [102X] Move pfparticle storage earlier to avoid double filling
  core/plugins/NtupleWriter.cc
Labels: Passed, RunII_102X_v1

#1199 [102X] Rekey PUPPI jet constituents
  core/plugins/RekeyJets.cc
  core/python/ntuple_generator.py
  examples/config/ExampleJetConstituents.xml
  examples/src/ExampleModuleJetConstituents.cxx
Labels: Passed, RunII_102X_v1

#1200 [102X] preliminary JER SFs for 2018 MC
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK4PF.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK4PFPuppi.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK4PFchs.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK8PF.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK8PFPuppi.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK8PFchs.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK4PF.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK8PF.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK4PF.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK4PFPuppi.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK4PFchs.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK8PF.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK8PFPuppi.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK8PFchs.txt
  common/include/JetCorrections.h
  common/src/JetCorrections.cxx
Labels: Passed, RunII_102X_v1

#1201 [102X] add functions to calculate raw scores of DeepBoosted tagger
  core/include/TopJet.h
Labels: Passed, RunII_102X_v1

#1203 [102X] Do original vs reco check for subjets of (Gen)TopJets in ExampleJetConstituents
  examples/config/ExampleJetConstituents.xml
  examples/src/ExampleModuleJetConstituents.cxx
Labels: Passed, RunII_102X_v1

#1202 [102X] Add rekey options to HOTVR & XCone producers, use it on PUPPI jets
  core/plugins/HOTVRProducer.cc
  core/plugins/RekeyJets.cc
  core/plugins/XConeProducer.cc
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1204 [102X] Simplify genparticle pruning into 1 module to possibly save some RSS memory
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1205 add Selection for recalculated metfilter related to ecalBadCalib
  common/include/NSelections.h
  common/src/CommonModules.cxx
Labels: Passed, RunII_102X_v1

#1206 [102X] Remove unused btagging algos
  core/python/ntuple_generator.py
Labels: Passed, RunII_102X_v1

#1207 [102X] switch off addition of dummy xcone genjets
  core/plugins/GenXConeProducer.cc
  core/python/ntuplewriter_mc_2018_dijet.py
Labels: Passed, RunII_102X_v1

#1209 [102X] Use unique_ptr to avoid raw ptr leaking in GenXConeProducer
  core/plugins/GenXConeProducer.cc
Labels: Passed, RunII_102X_v1

#1210 [10_2_X] increase requested RSS
  scripts/crab/crab_template.py
Labels: TestsRunning
