Repository UHH2/UHH2, pull requests merged in 2019-10, with the labels that each got.

#1436 [102X] Fixed small bugs
  common/datasets/RunII_102X_v1/2016v3/MC_WWToLNuQQ.xml
  common/src/CommonModules.cxx
Labels: Passed, RunII_102X_v1

#1439 [102X] set JER MCTruth to 0 for all jets with pt<35 in 2017
  common/src/JetCorrections.cxx
Labels: RunII_102X_v1, TestsRunning

#1440 [102X] Reorder CommonModule process so returns go last
  common/src/CommonModules.cxx
  examples/src/ExampleModule.cxx
Labels: Passed, RunII_102X_v1

#1441 [102X] Update default JEC/JER, + read JER SF text files
  JetMETObjects/README
  JetMETObjects/interface/JetResolution.h
  JetMETObjects/interface/JetResolutionObject.h
  JetMETObjects/interface/Utilities.h
  JetMETObjects/src/JetResolution.cc
  JetMETObjects/src/JetResolutionObject.cc
  common/data/2018/Autumn18_V7_MC_SF_AK4PFPuppi.txt
  common/data/2018/Autumn18_V7_MC_SF_AK4PFchs.txt
  common/data/2018/Autumn18_V7_MC_SF_AK8PFPuppi.txt
  common/data/2018/Autumn18_V7_MC_SF_AK8PFchs.txt
  common/include/JetCorrectionSets.h
  common/include/JetCorrections.h
  common/src/CommonModules.cxx
  common/src/JetCorrectionSets.cxx
  common/src/JetCorrections.cxx
Labels: Passed, RunII_102X_v1

#1444 [102v2] Add CMSSW packages for JEC/R
  scripts/install.sh
Labels: Passed, RunII_102X_v2

#1445 [102v2] Port across changes from 102v1 branch
  common/data/2018/Autumn18_V7_MC_PtResolution_AK4PF.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK4PFPuppi.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK4PFchs.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK8PF.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK8PFPuppi.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK8PFchs.txt
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-1000.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-1200.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-1400.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-1600.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-1800.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-2000.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-2500.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-3000.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-3500.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-4000.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-4500.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-500.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-600.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_M-800.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-1000.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-1600.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-1800.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-2000.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-2500.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-3000.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-3500.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-4500.xml
  common/datasets/RunII_102X_v1/2016v2/BulkGravToWW/BulkGravToWW_narrow_M-800.xml
  common/include/CleaningModules.h
  common/include/CommonModules.h
  common/include/JetCorrectionSets.h
  common/include/JetCorrections.h
  common/include/NSelections.h
  common/include/ObjectIdUtils.h
  common/include/PhotonIds.h
  common/src/CleaningModules.cxx
  common/src/CommonModules.cxx
  common/src/JetCorrectionSets.cxx
  common/src/JetCorrections.cxx
  examples/src/ExampleModule.cxx
  scripts/check2017SamplesPileup.py
Labels: Passed, RunII_102X_v2

#1446 [102v2] More things during installation
  scripts/install.csh
  scripts/install.sh
Labels: Passed, RunII_102X_v2

#1448 [102X] 2016 legacy JSON file
  common/data/2016/Cert_271036-284044_13TeV_PromptReco_Collisions16_JSON.root
Labels: Passed, RunII_102X_v1

#1447 [102v2] Use group storage area instead of individual user areas for CRAB jobs
  scripts/crab/crab_template.py
Labels: RunII_102X_v2

#1449 [102X] Fix order in CommonModules so exits first
  common/src/CommonModules.cxx
Labels: Passed, RunII_102X_v1

#1450 [102X] Added 2016 muon and electron SFs
  common/data/2016/EGM2D_BtoH_GT20GeV_RecoSF_Legacy2016.root
  common/data/2016/MuonID_EfficienciesAndSF_average_RunBtoH.root
  common/data/2016/MuonIso_EfficienciesAndSF_average_RunBtoH.root
Labels: RunII_102X_v1

#1452 [102X] Added scale variation handles
  common/include/MCWeight.h
  common/src/MCWeight.cxx
Labels: Passed, RunII_102X_v1

#1453 Skip scale variation if less than 9 systweights exist
  common/src/MCWeight.cxx
Labels: Passed, RunII_102X_v1
