Repository UHH2/UHH2, pull requests merged in 2020-11, with the labels that each got.

#1538 [102X] cherry-pick: Fix order in CommonModules so exits first
  common/src/CommonModules.cxx
Labels: Passed, RunII_102X_v2

#1539 [106X] cherry-pick: Fix order in CommonModules so exits first
  common/src/CommonModules.cxx
Labels: Passed, RunII_106X_v1

#1540 [102Xv2] Port #1450: Added 2016 muon and electron SFs
  common/data/2016/EGM2D_BtoH_GT20GeV_RecoSF_Legacy2016.root
  common/data/2016/MuonID_EfficienciesAndSF_average_RunBtoH.root
  common/data/2016/MuonIso_EfficienciesAndSF_average_RunBtoH.root
Labels: RunII_102X_v2

#1541 [102Xv2] Port of #1463: Skip leading jet(s) in ttbar reconstruction
  common/include/TTbarReconstruction.h
  common/src/TTbarReconstruction.cxx
Labels: Passed, RunII_102X_v2

#1542 [102Xv2] Use slc7 SCRAM_ARCH for EL7 machines
  scripts/install.sh
Labels: Passed, RunII_102X_v2

#1543 [106X] Port 1450, 1463, 1514, 1515, 1534
  common/data/2016/EGM2D_BtoH_GT20GeV_RecoSF_Legacy2016.root
  common/data/2016/MuonID_EfficienciesAndSF_average_RunBtoH.root
  common/data/2016/MuonIso_EfficienciesAndSF_average_RunBtoH.root
  common/include/DetectorCleaning.h
  common/include/TTbarReconstruction.h
  common/src/DetectorCleaning.cxx
  common/src/TTbarReconstruction.cxx
  common/src/TopPtReweight.cxx
  core/plugins/NtupleWriter.cc
  core/plugins/NtupleWriter.h
Labels: Passed, RunII_106X_v1

#1535 Run ii 106 x v1-- Add config options for UL16
  core/python/ntuple_generator.py
  core/python/ntuplewriter_data_UL16postVFP.py
  core/python/ntuplewriter_data_UL16preVFP.py
  core/python/ntuplewriter_mc_UL16postVFP.py
  core/python/ntuplewriter_mc_UL16preVFP.py
Labels: Passed, RunII_106X_v1
