Repository UHH2/UHH2, pull requests merged in 2020-01, with the labels that each got.

#1477 [106X] changed used CMSSW release to 10_6_8
  scripts/install.csh
  scripts/install.sh
Labels: Passed, RunII_106X_v1

#1467 Run ii 106 x v1
  .gitignore
  JetMETObjects/README
  JetMETObjects/interface/JetResolution.h
  JetMETObjects/interface/JetResolutionObject.h
  JetMETObjects/interface/Utilities.h
  JetMETObjects/src/JetResolution.cc
  JetMETObjects/src/JetResolutionObject.cc
  common/data/2016/Spring16_25nsV10_MC_PtResolution_AK4PFchs.txt
  common/data/2016/Spring16_25nsV10_MC_PtResolution_AK8PFchs.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK4PF.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK4PFPuppi.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK4PFchs.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK8PF.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK8PFPuppi.txt
  common/data/2016/Summer16_25nsV1_MC_PtResolution_AK8PFchs.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK4PF.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK4PFPuppi.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK4PFchs.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK8PF.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK8PFPuppi.txt
  common/data/2017/Fall17_V3_MC_PtResolution_AK8PFchs.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK4PF.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK4PFPuppi.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK4PFchs.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK8PF.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK8PFPuppi.txt
  common/data/2018/Autumn18_V1_MC_PtResolution_AK8PFchs.txt
  common/data/2018/Autumn18_V4_MC_PtResolution_AK4PF.txt
  common/data/2018/Autumn18_V4_MC_PtResolution_AK4PFPuppi.txt
  common/data/2018/Autumn18_V4_MC_PtResolution_AK4PFchs.txt
  common/data/2018/Autumn18_V4_MC_PtResolution_AK8PF.txt
  common/data/2018/Autumn18_V4_MC_PtResolution_AK8PFPuppi.txt
  common/data/2018/Autumn18_V4_MC_PtResolution_AK8PFchs.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK4PF.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK4PFPuppi.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK4PFchs.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK8PF.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK8PFPuppi.txt
  common/data/2018/Autumn18_V7_MC_PtResolution_AK8PFchs.txt
  common/include/JetCorrectionSets.h
  common/include/JetCorrections.h
  common/src/JetCorrectionSets.cxx
  common/src/JetCorrections.cxx
  common/test/test_JER.cpp
  examples/src/ExampleModuleSystematics.cxx
  scripts/crab/countNumberEvents.C
  scripts/crab/multicrab.py
  scripts/crab/readaMCatNloEntries.py
Labels: Passed, RunII_106X_v1

#1483 [106X] Add ability to specify particular JEC uncertainty source
  common/src/JetCorrections.cxx
  examples/config/ExampleSystematics.xml
Labels: Passed, RunII_106X_v1

#1482 [102v2] Add ability to specify particular JEC uncertainty source
  common/src/JetCorrections.cxx
  examples/config/ExampleSystematics.xml
Labels: Passed, RunII_102X_v2

#1481 [102v1] Add ability to specify particular JEC uncertainty source
  common/src/JetCorrections.cxx
  examples/config/ExampleSystematics.xml
Labels: Passed, RunII_102X_v1

#1484 [102Xv1] Clone UHH2-datasets repo as part of install script
  scripts/install.sh
Labels: Passed, RunII_102X_v1

#1485 [102Xv2] Clone UHH2-datasets repo as part of install script
  scripts/install.csh
  scripts/install.sh
Labels: Passed, RunII_102X_v2

#1486 [106X] Clone UHH2-datasets repo as part of install script
  scripts/install.csh
  scripts/install.sh
Labels: Passed, RunII_106X_v1
